/*
 * Browser notifications, inside the service worker.
 *
 * The worker itself is generated by vite-plugin-pwa (generateSW), which pulls
 * this file in with `importScripts` (see `workbox.importScripts` in
 * vite.config.ts). It is plain JavaScript because nothing bundles it, and it
 * talks to no origin of its own: the browser's push service wakes it, and it
 * only ever opens this app's own pages.
 *
 * The server sends `{title, body, link, kind}` (the back's Web Push adapter).
 * A link that is not a plain in-app path opens Today, the same rule as
 * `pushPath` in src/lib/platform/pushLink.ts, which the app applies again
 * when the tap reaches it.
 */

/* The message an open tab receives on a tap; PUSH_TAP_MESSAGE in src/lib/platform/web.ts. */
const PUSH_TAP_MESSAGE = 'lexpad:push-tap';
const FALLBACK_TITLE = 'Lexpad';
const ICON = '/icons/icon-192.png';

function safePath(link) {
  if (typeof link !== 'string') return '/';
  if (!link.startsWith('/') || link.startsWith('//') || link.includes('\\')) return '/';
  for (const char of link) {
    const code = char.charCodeAt(0);
    if (code <= 0x20 || code === 0x7f) return '/';
  }
  return link;
}

function readPayload(event) {
  if (!event.data) return {};
  try {
    const body = event.data.json();
    return typeof body === 'object' && body !== null ? body : {};
  } catch {
    return { body: event.data.text() };
  }
}

self.addEventListener('push', (event) => {
  const payload = readPayload(event);
  const title = typeof payload.title === 'string' && payload.title !== '' ? payload.title : FALLBACK_TITLE;
  const body = typeof payload.body === 'string' ? payload.body : '';
  const link = safePath(payload.link);
  const kind = typeof payload.kind === 'string' ? payload.kind : '';
  event.waitUntil(
    Promise.all([
      self.registration.showNotification(title, {
        body,
        icon: ICON,
        badge: ICON,
        data: { link, kind },
      }),
      // Tell any open tab, so the bell on Today shows the dot at once. The
      // string matches PUSH_RECEIVED_MESSAGE in src/lib/platform/web.ts.
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windows) => {
        for (const client of windows) client.postMessage({ type: 'lexpad:push-received' });
      }),
    ]),
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const link = safePath(event.notification.data && event.notification.data.link);
  event.waitUntil(
    (async () => {
      const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      const open = windows.find((client) => new URL(client.url).origin === self.location.origin);
      if (open) {
        // The app routes the link itself, so a tab that is already open keeps
        // its state instead of reloading.
        await open.focus();
        open.postMessage({ type: PUSH_TAP_MESSAGE, link });
        return;
      }
      await self.clients.openWindow(new URL(link, self.location.origin).href);
    })(),
  );
});
